name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Set package version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          REF="${GITHUB_REF_NAME}"
          # Extract first SemVer from tag ref (supports v1.2.3, v.1.2.3, 1.2.3, and pre-releases/build meta)
          VERSION=$(printf "%s" "$REF" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z\.-]+)?' | head -n1)
          if [ -z "$VERSION" ]; then
            echo "Could not extract SemVer from tag '$REF'" >&2
            exit 1
          fi
          echo "Setting package.json version to $VERSION"
          npm version --no-git-tag-version "$VERSION"
      - run: npm ci
      - run: npm test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
