name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Set package version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          REF="${{ github.event.release.tag_name }}"
          if [ -z "$REF" ]; then REF="$GITHUB_REF_NAME"; fi
          echo "Using tag ref: $REF"
          # Extract first SemVer from tag (supports v1.2.3, v.1.2.3, 1.2.3, prereleases/build meta)
          VERSION=$(printf "%s" "$REF" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z\.-]+)?' | head -n1)
          if [ -z "$VERSION" ]; then
            echo "Could not extract SemVer from tag '$REF'" >&2
            exit 1
          fi
          echo "Setting package.json version to $VERSION and persisting to main"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          npm version --no-git-tag-version "$VERSION"
          git add package.json package-lock.json || true
          if git diff --cached --quiet; then
            echo "No version changes to commit"
          else
            git commit -m "chore(release): bump to v$VERSION"
            git push origin main
          fi
      - run: npm ci
      - run: npm test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
